name: Publish docs to head
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history and tags are fetched

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Restore Cached Dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs-material and mike
        run: |
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check -r requirements.txt

      - name: Deploy HEAD
        run: |
          git fetch origin gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git pull origin gh-pages --rebase
            git checkout main
          fi
      
          mike deploy head --push
          # mike set-default head --push
