- name: Force change in release branch /docs
  run: |
    echo "Built: $(date)" > docs/.buildinfo
    git add docs/.buildinfo
    git commit -m "Trigger rebuild with updated .buildinfo" || echo "Nothing to commit"
